import type { Locale } from "@/app/[lang]/dictionaries";

/**
 * Canonical origin for every absolute URL the site emits — `metadataBase`,
 * canonicals, hreflang alternates, the sitemap and the JSON-LD graph.
 *
 * Overridable so a preview deployment describes itself instead of claiming to be
 * production: setting `NEXT_PUBLIC_SITE_URL` on a Vercel preview keeps its
 * canonicals pointing at the preview, which stops Google from indexing a branch
 * build under the real domain.
 */
export const SITE_ORIGIN = (
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://burakhasici.com"
).replace(/\/+$/, "");

export const SITE_NAME = "Burak Haşıcı";

/**
 * The same name, typed the ways people actually type it: a search box on a
 * non-Turkish keyboard produces "Burak Hasici", and the site calls itself BH in
 * its own wordmark. Google reconciles diacritics well enough on its own, but
 * `alternateName` is the one place to say it outright — and this site is
 * competing against LinkedIn and Instagram profiles for the same name, where
 * every explicit signal counts.
 */
export const SITE_ALTERNATE_NAMES = ["Burak Hasici", "BH"];

/** Stable node ids, so the graph's nodes can reference each other rather than
 * repeating themselves — and so other pages can point at the same Person. */
export const PERSON_ID = `${SITE_ORIGIN}/#person`;
export const WEBSITE_ID = `${SITE_ORIGIN}/#website`;

/**
 * The share card, generated by `app/opengraph-image.tsx`.
 *
 * Spread into every `openGraph`/`twitter` block by hand rather than left to the
 * file convention: metadata merges shallowly, so the moment a nested segment
 * defines `openGraph` at all, the parent's block — auto-generated image included
 * — is replaced wholesale. Relative on purpose, so it resolves against
 * `metadataBase` and a preview deployment serves its own copy.
 */
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "Burak Haşıcı — Software Engineer",
};

/** Open Graph wants `language_TERRITORY`, not the bare tag used for routing. */
export const OG_LOCALE: Record<Locale, string> = {
  en: "en_US",
  tr: "tr_TR",
};

/**
 * Locale-prefixed path, matching what `proxy.ts` actually serves: English is the
 * default locale and stays prefix-less, Turkish lives under `/tr`. This is the
 * same convention as `projectHref` in `lib/projects.ts` — if one changes, both do,
 * or the canonical URL stops matching the URL a visitor is on.
 */
export const localePath = (lang: Locale, path = "/"): string => {
  const suffix = path === "/" ? "" : path;
  return lang === "tr" ? `/tr${suffix}` : suffix || "/";
};

export const localeUrl = (lang: Locale, path = "/"): string =>
  `${SITE_ORIGIN}${localePath(lang, path)}`;

/**
 * The hreflang set for one page, in both locales plus `x-default`. Google uses
 * `x-default` for visitors whose language matches neither — English, here, since
 * it is the site's default locale.
 */
export const languageAlternates = (path = "/") => ({
  en: localeUrl("en", path),
  tr: localeUrl("tr", path),
  "x-default": localeUrl("en", path),
});

/**
 * The inverse of `localePath`: strips a `/tr` prefix back off, so a path can be
 * re-prefixed for the other locale. `/tr` and `/tr/` both come back as `/`,
 * which is the case the language switcher used to get wrong — it concatenated
 * `/tr` onto the home path `/` and produced `/tr/`, a URL that only exists to
 * 308 to `/tr`. Google logged that hop as "Page with redirect".
 */
export const stripLocalePrefix = (pathname: string): string =>
  pathname.replace(/^\/tr(?=\/|$)/, "").replace(/\/$/, "") || "/";
