import type { ComponentType, SVGProps } from "react";
import {
  AppleDark,
  Atlassian,
  Bitbucket,
  Bootstrap5,
  C,
  Dart,
  Figma,
  FramerDark,
  Git,
  GitHubDark,
  GraphQL,
  Java,
  JavaScript,
  Jest,
  Jira,
  MaterialUI,
  Microsoft,
  MongoDB,
  Miro,
  NextJs,
  PostgreSQL,
  Python,
  React as ReactLogo,
  ReactQuery,
  Redux,
  Sketch,
  Slack,
  Storybook,
  SvelteJS,
  Swift,
  TailwindCSS,
  TypeScript,
  VisualStudioCode,
  VercelDark,
  Vitest,
} from "developer-icons";

export type SkillIconComponent = ComponentType<
  Partial<SVGProps<SVGSVGElement>> & { size?: number }
>;

export const SKILL_ICON_COMPONENTS = {
  apple: AppleDark,
  atlassian: Atlassian,
  bitbucket: Bitbucket,
  bootstrap: Bootstrap5,
  c: C,
  dart: Dart,
  figma: Figma,
  framer: FramerDark,
  git: Git,
  github: GitHubDark,
  graphql: GraphQL,
  java: Java,
  javascript: JavaScript,
  jest: Jest,
  jira: Jira,
  materialUi: MaterialUI,
  microsoft: Microsoft,
  mongodb: MongoDB,
  miro: Miro,
  nextjs: NextJs,
  postgresql: PostgreSQL,
  python: Python,
  react: ReactLogo,
  reactQuery: ReactQuery,
  redux: Redux,
  sketch: Sketch,
  slack: Slack,
  storybook: Storybook,
  svelte: SvelteJS,
  swift: Swift,
  tailwind: TailwindCSS,
  typescript: TypeScript,
  vscode: VisualStudioCode,
  vercel: VercelDark,
  vitest: Vitest,
} as const satisfies Record<string, SkillIconComponent>;

export type SkillIconId = keyof typeof SKILL_ICON_COMPONENTS;
